name: 'Run Terraform'
description: 'Invoke Terraform API to run Terraform'
inputs:
  workSpaceName:
    description: 'Terraform workspace name'
    required: true
  organizationName:
    description: 'Terraform organization Name'
    required: true
  terraformToken:
    description: 'Terraform Token'
    required: true
  terraformHost:
    description: 'Terraform Host Name'
    required: true
  isDestroy:
    description: 'Specifies if this plan is a destroy plan, which will destroy all provisioned resources'
    required: true
  message:
    description: 'Specifies the message to be associated with this run.'
    required: true
outputs:
  runId: 
    description: 'The run ID'
runs:
  using: 'node12'
  main: 'index.js'

branding:
  icon: 'play'  
  color: 'green'